from django.contrib.auth import get_user_model
from rest_framework import authentication, exceptions
from rest_framework.permissions import BasePermission

from apps.accounts.models import Role
from apps.accounts.services import AuthFacade


class BearerTokenAuthentication(authentication.BaseAuthentication):
    """Authenticate API requests using the Bearer token generated by AuthFacade."""

    keyword = "Bearer"

    def authenticate(self, request):
        """Return an authenticated user when a valid Bearer token is provided."""
        header = authentication.get_authorization_header(request).decode("utf-8")
        if not header:
            return None

        parts = header.split()
        if len(parts) != 2 or parts[0] != self.keyword:
            raise exceptions.AuthenticationFailed("Invalid authorization header.")

        payload = self._decode(parts[1])
        user = self._get_user(payload.get("sub"))
        if not user.is_active:
            raise exceptions.AuthenticationFailed("User account is inactive.")
        return user, payload

    def _decode(self, token):
        """Decode the access token and convert token errors into authentication failures."""
        try:
            return AuthFacade.decode_token(token)
        except Exception as exc:
            raise exceptions.AuthenticationFailed("Invalid or expired token.") from exc

    def _get_user(self, user_id):
        """Load the authenticated user from the token subject."""
        User = get_user_model()
        try:
            user_pk = int(user_id)
        except (TypeError, ValueError) as exc:
            raise exceptions.AuthenticationFailed("Invalid token subject.") from exc

        try:
            return User.objects.prefetch_related("user_roles__role", "user_roles__role__permissions").get(id=user_pk)
        except User.DoesNotExist as exc:
            raise exceptions.AuthenticationFailed("Authenticated user was not found.") from exc


class IsAdministrativeStaffOrPresident(BasePermission):
    """Allow access only to administrative staff and the university president."""

    message = "Only administrative staff or the university president can access this API."
    allowed_roles = {Role.ADMINISTRATIVE_STAFF, Role.UNIVERSITY_PRESIDENT}

    def has_permission(self, request, view):
        """Return whether the authenticated user has an allowed management role."""
        user = getattr(request, "user", None)
        return bool(user and user.is_authenticated and user.has_role(self.allowed_roles))


class HasUserManagementPermission(BasePermission):
    """Allow user management APIs only to users with the user.manage permission."""

    message = "The authenticated user does not have permission to manage users."

    def has_permission(self, request, view):
        """Return whether the authenticated user has user management permission."""
        user = getattr(request, "user", None)
        return bool(user and user.is_authenticated and user.has_permission_code("user.manage"))


class HasUserReadPermission(BasePermission):
    """Allow read-only user APIs to users with the user.read or user.manage permission."""

    message = "The authenticated user does not have permission to read users."

    def has_permission(self, request, view):
        """Return whether the authenticated user has user read permission."""
        user = getattr(request, "user", None)
        return bool(user and user.is_authenticated and user.has_permission_code({"user.read", "user.manage"}))
