from django.contrib.auth import get_user_model
from rest_framework import authentication, exceptions
from apps.accounts.services import AuthFacade


class BearerTokenAuthentication(authentication.BaseAuthentication):
    """Authenticate API requests using the Bearer token generated by AuthFacade."""

    keyword = "Bearer"

    def authenticate(self, request):
        """Return an authenticated user when a valid Bearer token is provided."""
        header = authentication.get_authorization_header(request).decode("utf-8")
        if not header:
            return None
        parts = header.split()
        if len(parts) != 2 or parts[0] != self.keyword:
            raise exceptions.AuthenticationFailed("Invalid authorization header.")
        payload = self._decode(parts[1])
        user = self._get_user(payload.get("sub"))
        if not user.is_active:
            raise exceptions.AuthenticationFailed("User account is inactive.")
        return user, payload

    def _decode(self, token):
        """Decode the access token and convert token errors into authentication failures."""
        try:
            return AuthFacade.decode_token(token)
        except Exception as exc:
            raise exceptions.AuthenticationFailed("Invalid or expired token.") from exc

    def _get_user(self, user_id):
        """Load the authenticated user from the token subject."""
        User = get_user_model()
        try:
            return User.objects.prefetch_related("user_roles__role").get(id=int(user_id))
        except User.DoesNotExist as exc:
            raise exceptions.AuthenticationFailed("Authenticated user was not found.") from exc
