/** Renders the DesignSystemPage workspace and coordinates its API-driven interactions. */

import { AlertTriangle, CheckCircle2, Component, Info, Sparkles } from "lucide-react";
import { Button, Card, EmptyState, Input, PageHeader, ProgressRing, Select, StatusBadge, Textarea } from "../components/ui";

export function DesignSystemPage() {
  return <div className="page-stack"><PageHeader title="UniFlow design system" description="Reusable, accessible interaction patterns keep every role and module visually consistent." eyebrow="Experience architecture" />
    <section className="design-hero"><div><Sparkles /><h2>Clarity before decoration</h2><p>Components use semantic tokens, visible focus, motion preferences, responsive density and status labels that never rely on color alone.</p></div><div className="token-cloud"><span>Accessible</span><span>Responsive</span><span>Role-aware</span><span>RTL-ready</span><span>Consistent</span></div></section>
    <section className="design-grid"><Card><p className="eyebrow">Actions</p><h2>Buttons</h2><div className="component-row"><Button>Primary action</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Destructive</Button></div></Card><Card><p className="eyebrow">Status language</p><h2>Badges</h2><div className="component-row"><StatusBadge status="approved" /><StatusBadge status="under_review" /><StatusBadge status="pending" /><StatusBadge status="rejected" /></div></Card><Card><p className="eyebrow">Form controls</p><h2>Inputs</h2><div className="form-stack"><Input label="Course title" placeholder="Advanced software engineering" hint="Use the official catalog name." /><Select label="Status"><option>Published</option><option>Draft</option></Select><Textarea label="Description" rows={3} /></div></Card><Card><p className="eyebrow">Progress</p><h2>Data visualization</h2><div className="component-row"><ProgressRing value={72} label="complete" /><ProgressRing value={93} label="quality" /></div></Card></section>
    <section className="design-grid"><Card className="message-card message-success"><CheckCircle2 /><div><strong>Operation completed</strong><p>The change is persisted and recorded in the audit trail.</p></div></Card><Card className="message-card message-warning"><AlertTriangle /><div><strong>Review required</strong><p>This item is nearing its governance deadline.</p></div></Card><Card className="message-card message-info"><Info /><div><strong>Helpful context</strong><p>Supporting information appears without blocking the workflow.</p></div></Card><Card><EmptyState title="Purposeful empty state" message="Explain why the page is empty and provide the best next action." /></Card></section>
    <Card><div className="panel-heading"><div><p className="eyebrow">Architecture</p><h2>Component principles</h2></div><Component /></div><div className="principle-grid"><article><strong>Semantic tokens</strong><p>Color, radius, spacing and elevation are centralized in CSS variables.</p></article><article><strong>Composable states</strong><p>Loading, empty, error and success patterns share predictable anatomy.</p></article><article><strong>Keyboard first</strong><p>Dialogs trap focus, global search has a hotkey and navigation remains visible.</p></article><article><strong>Reduced motion</strong><p>Motion can be disabled through the user’s persisted experience preferences.</p></article></div></Card>
  </div>;
}
