/** Renders the FeedbackPage workspace and coordinates its API-driven interactions. */

import { useState } from "react";
import { Bug, Lightbulb, MessageSquareText, Plus, Sparkles, Star } from "lucide-react";
import { useAppSelector } from "../app/hooks";
import { selectAuth } from "../app/authSlice";
import { useCreateFeedbackMutation, useFeedbackQuery, useManageFeedbackMutation, useUsersQuery } from "../services/api";
import { Badge, Button, Card, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, Pagination, Select, StatusBadge, Textarea } from "../components/ui";
import { formatDate, getErrorMessage } from "../app/formatters";
import { useToast } from "../app/useToast";
import type { FeedbackItem } from "../types";

const feedbackIcons = { bug: Bug, idea: Lightbulb, ux: Sparkles, ai: MessageSquareText, other: MessageSquareText };
export function FeedbackPage() {
  const [page, setPage] = useState(1); const [open, setOpen] = useState(false); const [manage, setManage] = useState<FeedbackItem | null>(null);
  const { user } = useAppSelector(selectAuth); const canManage = Boolean(user?.permissions.includes("feedback.manage") || user?.permissions.includes("*"));
  const { data, isLoading, error } = useFeedbackQuery({ page });
  const { data: staff } = useUsersQuery({ is_active: "true", role: "AdministrativeStaff" }, { skip: !canManage });
  const [createFeedback, createState] = useCreateFeedbackMutation(); const [manageFeedback, manageState] = useManageFeedbackMutation(); const { show } = useToast();
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await createFeedback({ feedback_type: form.get("feedback_type"), title: form.get("title"), message: form.get("message"), page: window.location.pathname, rating: form.get("rating") ? Number(form.get("rating")) : null, metadata: { user_agent: navigator.userAgent.slice(0, 240), viewport: `${window.innerWidth}x${window.innerHeight}` } }).unwrap(); show("Feedback submitted. Thank you for improving UniFlow."); setOpen(false); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  async function update(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!manage) return; const form = new FormData(event.currentTarget); try { await manageFeedback({ id: manage.id, body: { status: form.get("status"), assigned_to: form.get("assigned_to") ? Number(form.get("assigned_to")) : null, admin_note: form.get("admin_note") } }).unwrap(); show("Feedback workflow updated"); setManage(null); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  return <div className="page-stack"><PageHeader title="Feedback and improvement center" description="Report a bug, suggest an idea or rate the experience. Every item has a transparent resolution status." action={<Button onClick={() => setOpen(true)}><Plus />Share feedback</Button>} />
    <section className="feedback-summary"><Card><Bug /><div><strong>Report friction early</strong><p>Page and device context are attached automatically without collecting sensitive content.</p></div></Card><Card><Lightbulb /><div><strong>Shape the roadmap</strong><p>Ideas remain visible with triage, ownership and resolution notes.</p></div></Card><Card><Sparkles /><div><strong>Improve AI and UX</strong><p>Separate feedback types make quality analytics actionable.</p></div></Card></section>
    {isLoading ? <LoadingState label="Loading feedback" /> : error ? <ErrorState /> : !data?.data.length ? <EmptyState title="No feedback yet" message="Be the first to help improve the university experience." action={<Button onClick={() => setOpen(true)}>Create feedback</Button>} /> : <Card className="table-card"><div className="table-scroll"><table><thead><tr><th>Feedback</th><th>Type</th><th>Status</th><th>Owner</th><th>Created</th>{canManage ? <th /> : null}</tr></thead><tbody>{data.data.map((item) => { const Icon = feedbackIcons[item.feedback_type as keyof typeof feedbackIcons] || MessageSquareText; return <tr key={item.id}><td><div className="table-title-icon"><span><Icon /></span><div><strong>{item.title}</strong><small>{item.message}</small></div></div></td><td><Badge tone="info">{item.feedback_type}</Badge></td><td><StatusBadge status={item.status} /></td><td>{item.assigned_to_name || "Unassigned"}</td><td>{formatDate(item.created_at)}</td>{canManage ? <td><Button variant="ghost" onClick={() => setManage(item)}>Manage</Button></td> : null}</tr>; })}</tbody></table></div><Pagination page={page} pages={data.pagination?.pages || 1} onChange={setPage} /></Card>}
    {open ? <Modal title="Share feedback" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={create}><Select name="feedback_type" label="Feedback type" required><option value="idea">Product idea</option><option value="bug">Bug</option><option value="ux">UX and visual design</option><option value="ai">AI answer quality</option><option value="other">Other</option></Select><Select name="rating" label="Experience rating"><option value="">No rating</option>{[5,4,3,2,1].map((value) => <option value={value} key={value}>{value} / 5</option>)}</Select><div className="form-span-2"><Input name="title" label="Short title" required maxLength={180} /></div><div className="form-span-2"><Textarea name="message" label="What happened or what should improve?" hint="Do not include passwords, financial details or other sensitive information." required rows={7} /></div><div className="modal-actions form-span-2"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={createState.isLoading}><Star />Submit feedback</Button></div></form></Modal> : null}
    {manage ? <Modal title="Manage feedback" onClose={() => setManage(null)}><form className="form-stack" onSubmit={update}><Select name="status" label="Status" defaultValue={manage.status}><option value="new">New</option><option value="triaged">Triaged</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></Select><Select name="assigned_to" label="Owner" defaultValue={manage.assigned_to || ""}><option value="">Unassigned</option>{staff?.data.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</Select><Textarea name="admin_note" label="Resolution note" defaultValue={manage.admin_note} rows={5} /><div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setManage(null)}>Cancel</Button><Button disabled={manageState.isLoading}>Save changes</Button></div></form></Modal> : null}
  </div>;
}
