/** Renders the NotificationsPage workspace and coordinates its API-driven interactions. */

import { useState } from "react";
import { Bell, BellRing, CheckCheck, Clock3, Megaphone, Pin, Send, Settings2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import {
  useBroadcastNotificationMutation, useNotificationActionMutation, useNotificationDigestQuery,
  useNotificationPreferencesQuery, useNotificationsQuery, useReadAllNotificationsMutation,
  useReadNotificationMutation, useRolesQuery, useUpdateNotificationPreferencesMutation,
} from "../services/api";
import { useAppSelector } from "../app/hooks";
import { selectAuth } from "../app/authSlice";
import { Badge, Button, Card, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, Pagination, Select, StatusBadge, Textarea } from "../components/ui";
import { formatDate, getErrorMessage } from "../app/formatters";
import { useToast } from "../app/useToast";

export function NotificationsPage() {
  const [page, setPage] = useState(1); const [unread, setUnread] = useState(""); const [category, setCategory] = useState(""); const [priority, setPriority] = useState("");
  const [broadcastOpen, setBroadcastOpen] = useState(false); const [settingsOpen, setSettingsOpen] = useState(false);
  const navigate = useNavigate(); const { user } = useAppSelector(selectAuth); const canBroadcast = Boolean(user?.permissions.includes("notifications.broadcast") || user?.permissions.includes("*"));
  const { data, isLoading, error } = useNotificationsQuery({ page, unread, category, priority });
  const { data: digest } = useNotificationDigestQuery({ period: "daily" });
  const { data: preferences } = useNotificationPreferencesQuery(); const { data: roles } = useRolesQuery(undefined, { skip: !canBroadcast });
  const [readNotification] = useReadNotificationMutation(); const [readAll, readAllState] = useReadAllNotificationsMutation(); const [action] = useNotificationActionMutation(); const [broadcast, broadcastState] = useBroadcastNotificationMutation(); const [updatePreferences, preferenceState] = useUpdateNotificationPreferencesMutation(); const { show } = useToast();
  async function openNotification(id: number, link: string, isRead: boolean) { if (!isRead) await readNotification(id).unwrap(); if (link) navigate(link); }
  async function perform(id: number, name: string) { try { await action({ id, action: name, ...(name === "snooze" ? { snoozed_until: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString() } : {}) }).unwrap(); show(name === "snooze" ? "Notification snoozed for 24 hours" : "Notification updated"); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  async function publish(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await broadcast({ title: String(form.get("title")), message: String(form.get("message")), category: String(form.get("category")), priority: String(form.get("priority")), link: String(form.get("link") || ""), role_ids: form.getAll("role_ids").map(Number) }).unwrap(); show("Notification published"); setBroadcastOpen(false); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  async function savePreferences(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await updatePreferences({ enabled_categories: form.getAll("categories").map(String), in_app_enabled: form.get("in_app_enabled") === "on", email_enabled: form.get("email_enabled") === "on", quiet_hours_start: String(form.get("quiet_hours_start") || "") || null, quiet_hours_end: String(form.get("quiet_hours_end") || "") || null }).unwrap(); show("Notification preferences saved"); setSettingsOpen(false); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  return <div className="page-stack"><PageHeader title="Notification center" description="Prioritize, pin, snooze and digest university updates without losing important context." action={<div className="page-actions"><Button variant="secondary" onClick={() => setSettingsOpen(true)}><Settings2 />Preferences</Button>{canBroadcast ? <Button onClick={() => setBroadcastOpen(true)}><Megaphone />Broadcast</Button> : null}</div>} />
    <section className="digest-strip"><div><span><BellRing /></span><div><p className="eyebrow">Daily digest</p><h2>{digest?.data.unread || 0} unread updates</h2><p>{digest?.data.urgent || 0} urgent · {digest?.data.total || 0} received today</p></div></div><div className="digest-categories">{Object.entries(digest?.data.categories || {}).map(([name, count]) => <Badge key={name} tone="info">{name} {count}</Badge>)}</div></section>
    <Card className="toolbar"><div className="filter-row"><select className="toolbar-select" value={unread} onChange={(event) => { setUnread(event.target.value); setPage(1); }}><option value="">All messages</option><option value="true">Unread</option><option value="false">Read</option></select><select className="toolbar-select" value={category} onChange={(event) => { setCategory(event.target.value); setPage(1); }}><option value="">All categories</option><option value="academic">Academic</option><option value="workflow">Workflow</option><option value="document">Document</option><option value="management">Management</option><option value="system">System</option></select><select className="toolbar-select" value={priority} onChange={(event) => { setPriority(event.target.value); setPage(1); }}><option value="">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select></div><Button variant="secondary" onClick={() => void readAll().unwrap()} disabled={readAllState.isLoading}><CheckCheck />Mark all read</Button></Card>
    {isLoading ? <LoadingState label="Loading notifications" /> : error ? <ErrorState /> : !data?.data.length ? <EmptyState title="You are all caught up" message="No notifications match the current filters." /> : <div className="notification-list">{data.data.map((item) => <Card key={item.id} className={`notification-card ${item.is_read ? "notification-read" : ""} priority-border-${item.priority}`}><span className="notification-icon"><Bell /></span><div><button onClick={() => void openNotification(item.id, item.link, item.is_read)}><div><strong>{item.title}</strong>{!item.is_read ? <span className="unread-dot" /> : null}{item.is_pinned ? <Pin /> : null}</div><p>{item.message}</p></button><footer><div className="badge-row"><Badge tone="info">{item.category}</Badge><StatusBadge status={item.priority} /></div><span>{formatDate(item.created_at)}</span></footer><div className="notification-actions"><Button variant="ghost" onClick={() => void perform(item.id, item.is_pinned ? "unpin" : "pin")}><Pin />{item.is_pinned ? "Unpin" : "Pin"}</Button><Button variant="ghost" onClick={() => void perform(item.id, "snooze")}><Clock3 />Snooze 24h</Button><Button variant="ghost" onClick={() => void perform(item.id, item.is_read ? "unread" : "read")}>{item.is_read ? "Mark unread" : "Mark read"}</Button></div></div></Card>)}</div>}
    <Pagination page={page} pages={data?.pagination?.pages || 1} onChange={setPage} />
    {broadcastOpen ? <Modal title="Publish a role-based notification" onClose={() => setBroadcastOpen(false)}><form className="form-grid" onSubmit={publish}><Input name="title" label="Title" required /><Select name="category" label="Category"><option value="system">System</option><option value="academic">Academic</option><option value="workflow">Workflow</option><option value="document">Document</option><option value="management">Management</option></Select><Select name="priority" label="Priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></Select><Input name="link" label="Action link" placeholder="/documents" /><div className="form-span-2"><Textarea name="message" label="Message" rows={5} required /></div><div className="form-span-2"><span className="field-label">Recipient roles</span><div className="choice-grid">{roles?.data.map((role) => <label className="choice-card" key={role.id}><input type="checkbox" name="role_ids" value={role.id} />{role.name}</label>)}</div></div><div className="modal-actions form-span-2"><Button type="button" variant="secondary" onClick={() => setBroadcastOpen(false)}>Cancel</Button><Button disabled={broadcastState.isLoading}><Send />Publish</Button></div></form></Modal> : null}
    {settingsOpen ? <Modal title="Notification preferences" onClose={() => setSettingsOpen(false)}><form className="form-stack" onSubmit={savePreferences}><div className="switch-row"><input type="checkbox" name="in_app_enabled" defaultChecked={preferences?.data.in_app_enabled ?? true} /><span><strong>In-app notifications</strong><small>Show updates in the notification center.</small></span></div><div className="switch-row"><input type="checkbox" name="email_enabled" defaultChecked={preferences?.data.email_enabled ?? false} /><span><strong>Email digest</strong><small>Prepare digest-ready preferences for connected email delivery.</small></span></div><div><span className="field-label">Enabled categories</span><div className="choice-grid">{["system","workflow","document","academic","management"].map((item) => <label className="choice-card" key={item}><input type="checkbox" name="categories" value={item} defaultChecked={!preferences || preferences.data.enabled_categories.includes(item)} />{item}</label>)}</div></div><div className="form-grid"><Input name="quiet_hours_start" type="time" label="Quiet hours start" defaultValue={preferences?.data.quiet_hours_start || ""} /><Input name="quiet_hours_end" type="time" label="Quiet hours end" defaultValue={preferences?.data.quiet_hours_end || ""} /></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setSettingsOpen(false)}>Cancel</Button><Button disabled={preferenceState.isLoading}>Save preferences</Button></div></form></Modal> : null}
  </div>;
}
