/** Renders the QuestionsPage workspace and coordinates its API-driven interactions. */

import { useState } from "react";
import { Bot, ExternalLink, MessageCircleQuestion, Search, ShieldCheck, Sparkles, ThumbsDown, ThumbsUp, UserRoundCheck } from "lucide-react";
import { useAppSelector } from "../app/hooks";
import { selectAuth } from "../app/authSlice";
import { useCreateQuestionMutation, useGenerateAnswerMutation, useHumanAnswerMutation, useQuestionsQuery, useRateAnswerMutation } from "../services/api";
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState, Modal, PageHeader, Pagination, ProgressRing, StatusBadge, Textarea } from "../components/ui";
import { formatDate, getErrorMessage } from "../app/formatters";
import { useToast } from "../app/useToast";

export function QuestionsPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [questionText, setQuestionText] = useState(""); const [humanTarget, setHumanTarget] = useState<number | null>(null);
  const { user } = useAppSelector(selectAuth); const canAnswer = Boolean(user?.permissions.includes("questions.answer") || user?.permissions.includes("*")); const canGenerate = canAnswer || Boolean(user?.permissions.includes("questions.create"));
  const { data, isLoading, error } = useQuestionsQuery({ page, search }); const [createQuestion, createState] = useCreateQuestionMutation(); const [generateAnswer, generateState] = useGenerateAnswerMutation(); const [humanAnswer, humanState] = useHumanAnswerMutation(); const [rateAnswer] = useRateAnswerMutation(); const { show } = useToast();
  async function submitQuestion(event: React.FormEvent) { event.preventDefault(); try { const created = await createQuestion({ text: questionText }).unwrap(); setQuestionText(""); if (canGenerate) await generateAnswer(created.data.id).unwrap(); show("Question submitted and securely processed"); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  async function submitHuman(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!humanTarget) return; const form = new FormData(event.currentTarget); try { await humanAnswer({ id: humanTarget, answer: String(form.get("answer")) }).unwrap(); show("Human-reviewed answer saved"); setHumanTarget(null); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  async function rate(id: number, rating: -1 | 1) { try { await rateAnswer({ id, rating }).unwrap(); show("Answer quality feedback recorded"); } catch (reason) { show(getErrorMessage(reason), "error"); } }
  return <div className="page-stack"><PageHeader title="Grounded university AI" description="Role-filtered retrieval, visible citations, confidence scoring and safe escalation instead of unsupported answers." />
    <Card className="ask-card"><span><Sparkles /></span><form onSubmit={submitQuestion}><label htmlFor="question">Ask a university question</label><Textarea id="question" value={questionText} onChange={(event) => setQuestionText(event.target.value)} placeholder="What is the process for requesting academic leave?" rows={4} required /><div><p><ShieldCheck />Personal identifiers are redacted before an external provider can be called.</p><Button disabled={createState.isLoading || generateState.isLoading}><Bot />{createState.isLoading || generateState.isLoading ? "Grounding answer…" : "Ask with sources"}</Button></div></form></Card>
    <Card className="toolbar"><div className="search-box"><Search /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search questions and answers" /></div></Card>
    {isLoading ? <LoadingState label="Loading conversations" /> : error ? <ErrorState /> : !data?.data.length ? <EmptyState title="No questions yet" message="Ask the knowledge base a question to start a traceable conversation." /> : <div className="question-list">{data.data.map((question) => <Card key={question.id} className="question-card"><header><div><StatusBadge status={question.status} /><Badge tone="neutral">{question.category || "general"}</Badge><Badge tone={question.priority === "Urgent" || question.priority === "High" ? "danger" : "neutral"}>{question.priority}</Badge></div><time>{formatDate(question.created_at)}</time></header><h2><MessageCircleQuestion />{question.text}</h2>{question.response ? <div className="answer-box"><div className="answer-main"><div className="answer-trust"><ProgressRing value={Math.round(question.response.confidence * 100)} label="confidence" size={92} /><div><strong>{question.response.safety_status.replaceAll("_", " ")}</strong><small>{question.response.provider} · {question.response.latency_ms ?? 0} ms</small></div></div><p>{question.response.answer}</p><div className="answer-actions"><span>Was this useful?</span><Button variant="ghost" aria-label="Helpful" onClick={() => void rate(question.id, 1)}><ThumbsUp />{question.response.user_rating === 1 ? "Helpful" : "Yes"}</Button><Button variant="ghost" aria-label="Not helpful" onClick={() => void rate(question.id, -1)}><ThumbsDown />{question.response.user_rating === -1 ? "Needs work" : "No"}</Button></div></div><aside className="source-panel"><div><ShieldCheck /><strong>{question.response.sources.length} authorized sources</strong></div>{question.response.sources.length ? question.response.sources.map((source, index) => <a key={source.id} href={source.url}><span>{index + 1}</span><div><strong>{source.title}</strong><small>v{source.index_version} · updated {formatDate(source.updated_at)}</small><p>{source.excerpt}</p></div><ExternalLink /></a>) : <p className="muted-copy">No reliable authorized source was found. This item was escalated for human review.</p>}</aside></div> : <p className="pending-answer">The question is waiting for grounded answer generation.</p>}{canAnswer && question.status === "Escalated" ? <footer><Button onClick={() => setHumanTarget(question.id)}><UserRoundCheck />Provide reviewed answer</Button></footer> : null}</Card>)}</div>}
    <Pagination page={page} pages={data?.pagination?.pages ?? 1} onChange={setPage} />
    {humanTarget ? <Modal title="Provide a reviewed answer" onClose={() => setHumanTarget(null)}><form className="form-stack" onSubmit={submitHuman}><Textarea name="answer" label="Verified answer" rows={9} required hint="Use the same evidence and authorization standards as an AI-generated response." /><div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setHumanTarget(null)}>Cancel</Button><Button disabled={humanState.isLoading}>Save reviewed answer</Button></div></form></Modal> : null}
  </div>;
}
