# Generated by Django 5.2.3 on 2026-06-15 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('document_type', models.CharField(choices=[('policy', 'Policy'), ('regulation', 'Regulation'), ('faq', 'FAQ'), ('guide', 'Guide'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('content', models.TextField()),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('role', 'Role restricted')], db_index=True, default='authenticated', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='documents', to='accounts.role')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', 'document_type'], name='documents_d_status_ec1dc9_idx')],
            },
        ),
    ]
