"""Defines the generated database schema migration 0002_document_content_checksum_document_index_version_and_more for the documents application."""

# Generated by Django 5.2.3 on 2026-06-21 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="document",
            name="index_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="knowledge_enabled",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("authenticated", "Authenticated users"),
                    ("role", "Role restricted"),
                    ("private", "Owner and document managers"),
                ],
                db_index=True,
                default="authenticated",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("policy", "Policy"),
                    ("regulation", "Regulation"),
                    ("faq", "FAQ"),
                    ("guide", "Guide"),
                    ("academic", "Academic"),
                    ("financial", "Financial"),
                    ("research", "Research"),
                    ("administrative", "Administrative"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("active", "Active (legacy)"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["knowledge_enabled", "status"],
                name="documents_d_knowled_68e14a_idx",
            ),
        ),
    ]
