# Generated by Django 5.1.15 on 2026-05-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_documen_fc21d0_idx',
            old_name='documents_docume_bf7d98_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_access__ab8fbf_idx',
            old_name='documents_access__94260f_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_is_acti_a803bb_idx',
            old_name='documents_is_acti_7eb1a8_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_title_3f6c9c_idx',
            old_name='documents_title_5f04e8_idx',
        ),
    ]
