# Generated by Django 5.1.15 on 2026-06-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_knowledge_base_audit"),
        (
            "documents",
            "0002_rename_documents_docume_bf7d98_idx_documents_documen_fc21d0_idx_and_more",
        ),
    ]

    operations = []
